### PR TITLE
v2 parse_pbp separate columns for home and visitors on_court

### PR DESCRIPTION
**Pull request by jpatak16**
I separated the players into home and visitors after they were put into the single on_court column. If you want to do it the way you mentioned let me know and I can change it.

### CODE REVIEW

**Comment by jpatak16** [comment]
Would the same code work for v1 as well? Do you have any v1 game_ids so I could check it?

**Comment by john-b-edwards** [comment]
I think this works, though I'm not sure it's the best approach.

```r
    for(c in paste0("player_", seq(1,10))){
      for(r in 1:nrow(pbp_parsed)){
        if(gsub("x_", "", pbp_parsed[r,c]) |> grepl(visitor_text_str)){
          pbp_parsed[r,"visitor_on_court"] = paste(pbp_parsed[r,"visitor_on_court"], pbp_parsed[r,c], sep = ";")}
        else{pbp_parsed[r,"home_on_court"] = paste(pbp_parsed[r,"home_on_court"], pbp_parsed[r,c], sep = ";")}
      }
    }
 ```

This looping approach at the end is fairly inefficient -- we loop over the entire PBP 10x.

```r
dplyr::mutate(
        subbed_in = grepl('Subbing in for ', events),
        subbed_out = grepl('Subbing out for ', events),
        player_on_play = gsub(
          "((.*)'s |-|by )",
          "",
          stringr::str_extract(events, "('s|by |-).*?$")
        ),
        player_on_play = gsub("\\(.*\\)", "", player_on_play),
        player_on_play = dplyr::case_when(player_on_play == "second time out." ~ "",
                                          T ~ player_on_play),
        player_on_play = trimws(player_on_play),
        player_on_play = gsub(dplyr::first(shortName_home), "", player_on_play),
        player_on_play = gsub(dplyr::first(shortName_visitor), "", player_on_play),
        player_on_play = dplyr::case_when(player_on_play == '' ~ NA_character_,
                                          player_on_play == "'s" ~ NA_character_,
                                          T ~ player_on_play),
        on_court_flag = dplyr::case_when(subbed_in ~ 1,
                                         subbed_out ~ 0,
                                         T ~ NA_real_)
      ) |>
      dplyr::filter(!is.na(player_on_play))
```

I think what may be better is rather than checking `events`, we check `visitorText` and `homeText`, then change these columns to something like `player_on_play_home` and `player_on_play_visitor`. Then, when we calculate on/off courts with the `group_modify`, we just do that twice, once for `_home` and once for `_visitor`.

I'll try to make these changes today or tomorrow if I have the chance.

R.e. V1, I think that one is much more straightforward. [Here is a quick example](https://www.ncaa.com/game/3914487/play-by-play) of V1 PBP. Note that lineup changes are formatted as:

```
Rebels lineup change (Amauri Hardy, Jonah Antonio, Marvin Coleman, Cheikh Mbacke Diong, Elijah Mitrou-Long)
```

The current code combines these lineups into a single `on_court` variable, but we could just as easily keep them in this format and have them already split by team.

**Comment by jpatak16** [comment]
When trying to separate the code into home and visitor portions, the code I have is running like it should work, but it is not picking up all 5 players on the court for each team for each stint. (It is picking up 5 per team some stints). I couldn't figure out why it was doing that. I'll wait and see if you can get it to work before I look into it further.

Also I will get the v1 done tomorrow, it doesn't look like it should be very difficult.

**Comment by john-b-edwards** [comment]
No worries, was able to knock out the V2 changes with some spare time before the Dragons game tonight. Let me know if those changes look good/are what you had in mind

**Comment by jpatak16** [comment]
Your changes look great!

**Comment by jpatak16** [comment]
For v1, if the extract_all_players only picks up <5 players and therefore there is a NA for the first stint for one of the teams, would you be ok with estimating the starters by using the second half starting lineup, rather than leaving it as an NA? Or should we just leave it be rather than putting something potentially wrong

**Comment by john-b-edwards** [comment]
We should leave it NA. If someone using this data wants to make that assumption, it should be pretty easy to do with the data in its current format, but I worry about cleaning messy PBP data by making assumptions that are not inherently obvious from the data set.

**Comment by john-b-edwards** [comment]
Okay! All of the examples I posted in discord seem to work properly. The lone exception is a single stint in `5921595`, but that's from genuinely messy PBP data and not anything wrong with our code, plus we're handling it correctly by `NA`ing that stint.



I'm going to write a couple quick tests, then merge. Thanks for the help @jpatak16 ! A+ work.

**Review by john-b-edwards — APPROVED** [review]

**Pull request merged**
